### ISSUE TITLE
Thank you for your reply. This is my feedback. 

### ISSUE THREAD

**Issue by hamadi1** [guigolab/lncATLAS#2]
Dear David, Thank you for your response. I can confirm that nothing happens when I type a gene name on the text box. I am using the front page to obtain the plots. I tried with google chrome and internet explorer many times but it doesn't work. Furthermore, I should mention that it takes long time to get access to the website. It looks that there is a server problem as well. I am living in South Korea. Please tell me how to solve this issue. Thank you. Best regards.

**Comment by davidmasp** [comment]
Duplicate of #1

**Comment by jliz85** [comment]
I am encountering exactly the same issue.
Bests, 
Julia
