### ISSUE TITLE
How lncATLAS choose the right isoform to represent one gene?

### ISSUE THREAD

**Issue by CrescentLuo** [guigolab/lncATLAS#3]
Hi, thank you for providing such a good database, while using this database I'm a little confused about how lncATLAS decide which isoform is the best one to represent one lncRNA? As different isoforms may have different RCI and different localization, I think it is very important to figure out this point.

**Comment by davidmasp** [comment]
Hi,
Thanks for your comment. lncATLAS currently uses gene-level quantifications so it's no possible to obtain the RCI (localisation) value for different isoforms of the same gene.
David
