### ISSUE TITLE
lncATLAS not responding!

### ISSUE THREAD

**Issue by dourongzhang** [guigolab/lncATLAS#4]
Dear lncATLAS team, today when I want to use resource of your website, I find the website doesn't response. For example, when I input MALAT1 into the box and press GO button, the website just doesn't response. I waited for 10 mins and nothing showed up. I use Google chrome and IE browser. I also tried to use lncATLAS in my phone and things go with the same way. Could you please check your website and figure what's going on? Thank you very much!

**Comment by toniher** [comment]
Dear @dourongzhang , the service was upgraded to use HTTPS and this provoked some issues. Our IT team just fixed it. Let us know in case you experienced any other problem.
