### ISSUE TITLE
Unable to access raw data from lncATLAS

### ISSUE THREAD

**Issue by shubhamc-iiitd** [guigolab/lncATLAS#5]
The raw data page of lncATLAS is irresponsive at the moment. In order to download data, the tables should appear below the line. Currently no such table is being displayed below the line. It would be very helpful, if you could look into the issue.
<img width="1509" alt="Screenshot 2023-02-03 at 2 45 17 PM" src="https://user-images.githubusercontent.com/111137559/216560238-46c70b52-1003-4b60-856b-4f285f74da2f.png">

**Comment by emi80** [comment]
Hi @shubhamc-iiitd, sorry for the late reply.

Thanks for reporting this. We are having a look into it and will let you know as the issue is solved.

Best

**Comment by shubhamc-iiitd** [comment]
@emi80 I am able to download all the raw data now. I am closing this issue as solved! Thanks!
